export interface Basic {
    Employee_Id: string,
    Employee_Name:string,
    Dob_Official: string,
    Dob_Actual: string,
    Gender: string,
    Reporting_Manager: string,
    Status: string,
    Joining_Date: string,
    Probation_Period: string,
    Email_ID: string,
    Contact_No: string,
    EMContact_No: string,
    Nationality: string,
    Religion: string,
    Lang_Known: {id:string, itemName: string}[],
    Permanent_Address: string,
    Present_Address: string,
    Design_At_Joining:string,
    Blood_Group:string,
    LinkedIN:string,
    Skype:string,
    Work_Location:string,
    Team:{id:string, itemName: string}[],
    Skill_Sets:{id:string, itemName: string}[]
}
